import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import Image from 'next/image'
export default function App({ Component, pageProps }: AppProps) {
  return (
    <div>
    <Head>
    <title>Green House Australia</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <Component {...pageProps} />
  </div>
  )
}
